### PR TITLE
Various minor updates

### PR DESCRIPTION
**Pull request by havardAasen**
- typo's
-  clang warnings
- GTK deprecation warnings
- ~~Refactor `UpdateWindowTitleWithProjectName()`~~

### CODE REVIEW

**Comment by havardAasen** [comment]
This PR got a bit messy, so I split it up into multiple PR's.

**Review by MaVaTi56 — APPROVED** [review]

**Review by MaVaTi56 — APPROVED** [review]

**Comment by MaVaTi56** [comment]
Yes, little commits for pull requests are better to proceed !
Many thanks for your valuable modifications.

**Comment by MaVaTi56** [comment]
Even more so with a crash on exit when compiling a Gtk+2  version (maintained for now...)
I will search which one the modifications is the cause.

**Comment by havardAasen** [comment]
Was this failure on Windows?
There been some months now, but I'm quite sure I tested this with both GTK 2 and 3 on Linux

**Comment by MaVaTi56** [comment]
No, on Linux "Ubuntu 20.04.4 LTS" (MATE) 64 bits. Gtk 2.24.32
I supposed you perhaps only focused on Gtk3...
Not looked more on this little problem for now - just put back gdk_cursor_unref() instead of the g_object_unref(). allocated with gdk_cursor_new_from_pixbuf().

**Pull request merged**
